### ISSUE TITLE
[1.11.2][Psi r1.1-46] Conjured Light Texture Issue

### ISSUE THREAD

**Issue by oitsjustjose** [Vazkii/Psi#313]
I hadn't seen another issue for this, but if there is one I'll delete this one promptly.

This one's an easy fix (in fact, I've fixed it on my own client instance) - looks like your code is looking for wisplarge.png for conjured light's particle texture, but Psi's packaged assets has named it wisp_large.png

I just checked this repo, and it is still wisp_large.png, so I figured it was worth mentioning! Renaming the file fixed my conjured light blocks looking glitchy (and causing a crash or two) :)

**Comment by Eufranio** [comment]
Was about to create a new issue, confirm that the file name is wrong 😄

**Comment by Haddadmj** [comment]
@oitsjustjose How did you change it?

**Comment by oitsjustjose** [comment]
I made a resource pack that put the properly named file in `/assets/psi/textures/misc/`

Just rename wisp_large.png to wisplarge.png and put it here.

**Comment by cragrim** [comment]
I'm also getting this error on Psi-r1.1-47.jar

```
[15:19:18] [Client thread/WARN]: Failed to load texture: psi:textures/misc/wisplarge.png
java.io.FileNotFoundException: psi:textures/misc/wisplarge.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[bzr.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cae.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:34) ~[byv.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:79) [bza.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) [bza.class:?]
	at vazkii.psi.client.fx.FXWisp.dispatchQueuedRenders(FXWisp.java:87) [FXWisp.class:?]
	at vazkii.psi.client.fx.ParticleRenderDispatcher.onRenderWorldLast(ParticleRenderDispatcher.java:46) [ParticleRenderDispatcher.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_105_ParticleRenderDispatcher_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166) [ForgeHooksClient.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at Reflector.callVoid(Reflector.java:547) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1912) [bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1590) [bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1361) [bqe.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
```

**Comment by Infinoid** [comment]
Do conjured lights look correct for you in Psi-r1.1-55.jar?

**Comment by oitsjustjose** [comment]
The latest release has fixed it for me, yes

**Comment by Infinoid** [comment]
Thanks for confirming the fix.  I think this issue can be closed.
