### ISSUE TITLE
PlayerData Crash

### ISSUE THREAD

**Issue by Doragoon01** [Vazkii/Psi#363]
I've been seeing this error a lot as i'm flying around in creative single player worlds.  I'm still unsure how to reproduce it, so i haven't tested it without other mods yet, or anything.

java.lang.NullPointerException: Unexpected error
	at vazkii.psi.common.core.handler.PlayerDataHandler.get(PlayerDataHandler.java:96)
	at vazkii.psi.common.core.handler.PlayerDataHandler$EventHandler.onRenderWorldLast(PlayerDataHandler.java:236)

while trying to reproduce this crash, i instead got this:

 java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at vazkii.psi.common.core.handler.PlayerDataHandler.cleanup(PlayerDataHandler.java:110)
	at vazkii.psi.common.core.handler.PlayerDataHandler$EventHandler.onServerTick(PlayerDataHandler.java:139)

Has this already been reported?

**Comment by Vince7778** [comment]
I have the exact same issue. After maybe 3 minutes on one world, my game suddenly crashes.

**Comment by 12foo** [comment]
Same thing for me. I'm pretty sure it's this line:

https://github.com/Vazkii/Psi/blob/0954426ec0aad4111102d586fb957fe496b9f697/src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java#L150

since safeExecute eventually adds the context to the list of delayed contexts, while that list is being looped over. I cloned the repo and I think I fixed it, but I can't get Psi to compile from master because of (apparently) old code in TileCADAssembler.java. So unfortunately no pull request. :(

**Comment by 12foo** [comment]
Oops. Sorry for the many messages; I kinda butterfingered the commit there.
