### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by ItsTheKais** [Vazkii/Psi#466]
[Log](https://pastebin.com/an41DzTh)

Occurred when loading a save after updating from r1.1-64 to r1.1-66. Reverting to r1.1-64 allows the save to be loaded.

* Psi r1.1-66
* AutoRegLib 1.3-24
* Forge 14.23.5.2796

**Comment by FoxMcloud5655** [comment]
I have this same issue.  I know it has to do with saving the persistent data, as evidenced by my own log:
```
java.lang.NullPointerException: name can't be null
	at java.io.FilePermission.init(FilePermission.java:191)
	at java.io.FilePermission.<init>(FilePermission.java:277)
	at java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:200)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at vazkii.psi.common.core.handler.PersistencyHandler.save(PersistencyHandler.java:90)
	at vazkii.psi.client.core.proxy.ClientProxy.savePersistency(ClientProxy.java:71)
	at vazkii.psi.common.network.message.MessageDataSync.lambda$handleMessage$0(MessageDataSync.java:42)
	at vazkii.psi.common.network.message.MessageDataSync$$Lambda$4280/628293113.run(Unknown Source)
	at vazkii.arl.util.ClientTicker.clientTickEnd(ClientTicker.java:59)
```

**Comment by FoxMcloud5655** [comment]
I also would like to point out that this does not happen when loading up a new world; only loading a previous one.

**Comment by yrsegal** [comment]
Until the build is out, this can be fixed by adding a file with your UUID to `.minecraft/psi_persistent`.

**Comment by FoxMcloud5655** [comment]
Unfortunately, I already had a file in the directory, and it's still crashing with the same error.  I did try letting the file regenerate.  Still no problems creating a new world with or without the file there.  The problem may lie deeper than that...  I'll see what I can do.
