### ISSUE TITLE
Crash with Terraqueous

### ISSUE THREAD

**Issue by FoxMcloud5655** [Vazkii/Psi#468]
Not sure if this is an issue on PSI's part, but posting it here anyways.  If it's not an issue with PSI (or if you don't really care), then please feel free to close this issue.

```
java.lang.ClassCastException: shetiphian.terraqueous.common.tileentity.TileEntityDoodad cannot be cast to vazkii.psi.common.block.tile.TileConjured
	at vazkii.psi.common.spell.trick.block.PieceTrickConjureBlock.conjure(PieceTrickConjureBlock.java:88)
	at vazkii.psi.common.spell.trick.block.PieceTrickConjureBlockSequence.execute(PieceTrickConjureBlockSequence.java:80)
```

**Comment by FoxMcloud5655** [comment]
Nicely done.  You're really good at this!
