### ISSUE TITLE
Little bit of a crash.....

### ISSUE THREAD

**Issue by ryuknightofflame** [Vazkii/Psi#48]
[01:18:31] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152) ~[bpo.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
	at vazkii.psi.api.spell.SpellContext.isInRadius(SpellContext.java:124) ~[SpellContext.class:?]
	at vazkii.psi.common.spell.selector.entity.PieceSelectorNearby.execute(PieceSelectorNearby.java:60) ~[PieceSelectorNearby.class:?]
	at vazkii.psi.api.spell.CompiledSpell$Action.execute(CompiledSpell.java:89) ~[CompiledSpell$Action.class:?]
	at vazkii.psi.api.spell.CompiledSpell.execute(CompiledSpell.java:55) ~[CompiledSpell.class:?]
	at vazkii.psi.api.spell.CompiledSpell.safeExecute(CompiledSpell.java:65) ~[CompiledSpell.class:?]
	at vazkii.psi.common.entity.EntitySpellProjectile.cast(EntitySpellProjectile.java:184) ~[EntitySpellProjectile.class:?]
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70184_a(EntitySpellProjectile.java:168) ~[EntitySpellProjectile.class:?]
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204) ~[wy.class:?]
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:125) ~[EntitySpellProjectile.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1860) ~[adm.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699) ~[le.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1829) ~[adm.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1661) ~[adm.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544) ~[le.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) ~[MinecraftServer.class:?]
	... 4 more
[01:18:31] [Server thread/ERROR]: This crash report has been saved to: C:\Users\joe\Desktop\MMc\MultiMC\instances\Magic and tech\minecraft\crash-reports\crash-2016-02-16_01.18.31-server.txt
[01:18:31] [Server thread/INFO]: Stopping server
[01:18:31] [Server thread/INFO]: Saving players
[01:18:31] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 2/16/16 1:18 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at vazkii.psi.api.spell.SpellContext.isInRadius(SpellContext.java:124)
	at vazkii.psi.common.spell.selector.entity.PieceSelectorNearby.execute(PieceSelectorNearby.java:60)
	at vazkii.psi.api.spell.CompiledSpell$Action.execute(CompiledSpell.java:89)
	at vazkii.psi.api.spell.CompiledSpell.execute(CompiledSpell.java:55)
	at vazkii.psi.api.spell.CompiledSpell.safeExecute(CompiledSpell.java:65)
	at vazkii.psi.common.entity.EntitySpellProjectile.cast(EntitySpellProjectile.java:184)
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70184_a(EntitySpellProjectile.java:168)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:125)
	at net.minecraft.world.World.func_72866_a(World.java:1860)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
	at net.minecraft.world.World.func_72870_g(World.java:1829)
	at net.minecraft.world.World.func_72939_s(World.java:1661)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at vazkii.psi.api.spell.SpellContext.isInRadius(SpellContext.java:124)
	at vazkii.psi.common.spell.selector.entity.PieceSelectorNearby.execute(PieceSelectorNearby.java:60)
	at vazkii.psi.api.spell.CompiledSpell$Action.execute(CompiledSpell.java:89)
	at vazkii.psi.api.spell.CompiledSpell.execute(CompiledSpell.java:55)
	at vazkii.psi.api.spell.CompiledSpell.safeExecute(CompiledSpell.java:65)
	at vazkii.psi.common.entity.EntitySpellProjectile.cast(EntitySpellProjectile.java:184)
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70184_a(EntitySpellProjectile.java:168)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:125)
	at net.minecraft.world.World.func_72866_a(World.java:1860)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
	at net.minecraft.world.World.func_72870_g(World.java:1829)

-- Entity being ticked --
Details:
	Entity Type: Psi.psi:spellProjectile (vazkii.psi.common.entity.EntitySpellProjectile)
	Entity ID: 373822
	Entity Name: entity.Psi.psi:spellProjectile.name
	Entity's Exact location: -149.76, 67.86, 310.92
	Entity's Block location: -150.00,67.00,310.00 - World: (-150,67,310), Chunk: (at 10,4,6 in -10,19; contains blocks -160,0,304 to -145,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -1.92, -0.87, 0.58
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1661)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
	Level name: Magic High Beginings
	All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/146481, l='Magic High Beginings', x=-143.83, y=69.00, z=309.30]]
	Chunk stats: ServerChunkCache: 501 Drop: 0
	Level seed: -2064872084
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: -96.00,64.00,252.00 - World: (-96,64,252), Chunk: (at 0,4,12 in -6,15; contains blocks -96,0,240 to -81,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 231591 game time, 231591 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 7973 (now: true), thunder time: 82015 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 298461680 bytes (284 MB) / 1089994752 bytes (1039 MB) up to 2982674432 bytes (2844 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx3200m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1724 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1724-universal.jar) 
	UCHIJAAAAAAAAA	Forge{11.15.1.1724} [Minecraft Forge] (forge-1.8.9-11.15.1.1724-universal.jar) 
	UCHIJAAAAAAAAA	bookshelfapi{2.3.1} [Bookshelf] (Bookshelf-1.8.9-2.3.1.jar) 
	UCHIJAAAAAAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAAAAAAA	intangible{0.0.22} [Intangible] (intangible-1.8.9-0.0.22.jar) 
	UCHIJAAAAAAAAA	JEI{2.26.0.154} [Just Enough Items] (jei_1.8.9-2.26.0.154.jar) 
	UCHIJAAAAAAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJAAAAAAAAA	neotech{2.3.5} [NeoTech] (NeoTech-1.8.9-2.3.5.jar) 
	UCHIJAAAAAAAAA	ProjectE{1.8.9-PE1.1.3} [ProjectE] (ProjectE-1.8.9-PE1.1.3.jar) 
	UCHIJAAAAAAAAA	Psi{beta-13} [Psi] (Psi-beta-13.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/146481, l='Magic High Beginings', x=-143.83, y=69.00, z=309.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[01:18:31] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\joe\Desktop\MMc\MultiMC\instances\Magic and tech\minecraft\crash-reports\crash-2016-02-16_01.18.31-server.txt
[01:18:31] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[01:18:31] [Server thread/INFO]: Saving worlds
[01:18:31] [Server thread/INFO]: Saving chunks for level 'Magic High Beginings'/Overworld
[01:18:31] [Server thread/INFO]: Saving chunks for level 'Magic High Beginings'/Nether
[01:18:31] [Server thread/INFO]: Saving chunks for level 'Magic High Beginings'/The End
[01:18:31] [Server thread/INFO] [journeymap]: Mapping halted in C:\Users\joe\Desktop\MMc\MultiMC\instances\Magic and tech\minecraft\journeymap\data\sp\Magic High Beginings\DIM0
[01:18:31] [Server thread/INFO] [FML]: Unloading dimension 0
[01:18:31] [Server thread/INFO] [FML]: Unloading dimension -1
[01:18:31] [Server thread/INFO] [FML]: Unloading dimension 1
[01:18:31] [Server thread/INFO] [FML]: Applying holder lookups
[01:18:31] [Server thread/INFO] [FML]: Holder lookups applied
[01:18:31] [Server thread/INFO] [ProjectE]: Completed server-stop actions.
[01:18:31] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[01:18:31] [Client thread/INFO] [FML]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

**Comment by JRoffel** [comment]
Could you please do all the following things:
1. Place error logs in pastebin, this is unreadable
2. Tell us how to reproduce
3. State versions of the mod, forge, Minecraft and java

**Comment by yrsegal** [comment]
Vazkii didn't check for null vectors, apparently.

**Comment by yrsegal** [comment]
https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/api/spell/SpellContext.java#L123-L125

Having a null check in here returning 'false' should solve this problem, I suppose.

**Comment by Vazkii** [comment]
No, there should be no null check there. The root of the problem is the fact that something else passed in null to it. If @ryuknightofflame could pass in a copy of the spell's JSON output that would help a lot.
