### ISSUE TITLE
"messageloopcastsync" error

### ISSUE THREAD

**Issue by 43DarkNero** [Vazkii/Psi#485]
So this happened to me and a friend of mine while loading up. Game loads up right, but after like... 40 seconds maybe even 2 minutes or so the game crashes! 
I've attached the full log to the issue.
Here's an excerpt of the issue.
```
Unexpected error

java.lang.NullPointerException: Unexpected error
	at vazkii.psi.common.network.message.MessageLoopcastSync.lambda$handleMessage$0(MessageLoopcastSync.java:47)
	at vazkii.arl.util.ClientTicker.clientTickEnd(ClientTicker.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_379_ClientTicker_clientTickEnd_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
[crash-2019-02-19_20.14.53-client.txt](https://github.com/Vazkii/Psi/files/2882793/crash-2019-02-19_20.14.53-client.txt)

**Comment by 43DarkNero** [comment]
Consistency is really off. Game may work, game may not work. It'll all a game of "does the game crash."
