### ISSUE TITLE
Psi Crash on Loading - Cannot Create Home Directory

### ISSUE THREAD

**Issue by warderbrad** [Vazkii/Psi#499]
While loading into multiplayer world minecraft crashes completely due to an exception from Psi.

It appears that it is trying to create a directory but my install is not being made to my %AppData% location and this is causing errors.  

Unexpected error

java.lang.RuntimeException: Couldn't create home directory!
	at vazkii.psi.common.core.handler.PersistencyHandler.init(PersistencyHandler.java:48)
	at vazkii.psi.client.core.handler.ClientTickHandler.clientTickEnd(ClientTickHandler.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_966_ClientTickHandler_clientTickEnd_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[crash-2019-04-27_15.16.34-client.txt](https://github.com/Vazkii/Psi/files/3124328/crash-2019-04-27_15.16.34-client.txt)

I found an issue in my %AppData% folder and am trying again.  Will update should it resolve.

**Comment by Kamefrede** [comment]
Any update on the situation? Does it still crash?

**Comment by Heaper327** [comment]
Same problem here:
[crash-2019-05-24_23.43.15-client.txt](https://github.com/Vazkii/Psi/files/3219101/crash-2019-05-24_23.43.15-client.txt)

**Comment by alxpettit** [comment]
Can confirm @Heaper327's solution works. Also, I got this crash right after migrating my `mods/` and `config/` directories to a fresh modded install. I wonder if it has something to do with a file or directory suddenly disappearing unexpectedly, somewhere in the `.minecraft`.

**Comment by Kamefrede** [comment]
Closing this as no relevant reports have come and seeing as Psi ditched this in 1.15.
